version: '3'
services:

## Logging

# search engine, storage
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.1.1
    ports:
    - 9200:9200

# logs visualizer
  kibana:
    image: docker.elastic.co/kibana/kibana:6.1.1
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601

  # log collector
  fluentbit:
    build: .
    ports:
    - 24231:24231
    - 24224:24224
    - 24224:24224/udp
    depends_on:
      - elasticsearch