version: '3'
services:

  ## Logging

  # search engine, storage
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.1.1
    ports:
    - 9200:9200

  # logs visualizer
  kibana:
    image: docker.elastic.co/kibana/kibana:6.1.1
    depends_on:
    - elasticsearch
    ports:
    - 5601:5601

  # log collector
  fluentbit-1:
    build: .
    depends_on:
    - elasticsearch
    volumes:
    - ${PWD}/conf1/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
    - ${PWD}/parsers/parsers.conf:/fluent-bit/etc/parsers.conf

  fluentbit-2:
    build: .
    depends_on:
    - elasticsearch
    volumes:
    - ${PWD}/conf2/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
    - ${PWD}/parsers/parsers.conf:/fluent-bit/etc/parsers.conf

  fluentbit-3:
    build: .
    depends_on:
    - elasticsearch
    volumes:
    - ${PWD}/conf3/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
    - ${PWD}/parsers/parsers.conf:/fluent-bit/etc/parsers.conf
