FROM alpine

RUN echo "1) this is a regular echo"

RUN echo "1) this is stdout" > /dev/stdout

RUN echo "1) this is stderr" > /dev/stderr

FROM alpine

RUN echo "2) this is a regular echo"

RUN echo "2) this is stdout" > /dev/stdout

RUN echo "2) this is stderr" > /dev/stderr
